INSERT INTO HOLIDAY (HOLIDAY_DATE,REASON,TYPE) VALUES ('1st Jan', 'Happy New Year', 'NATIONAL');
INSERT INTO HOLIDAY (HOLIDAY_DATE,REASON,TYPE) VALUES('15th Aug', 'Happy Independence Day', 'NATIONAL');
INSERT INTO HOLIDAY (HOLIDAY_DATE,REASON,TYPE) VALUES('2nd Oct', 'Mahatma Gandhi Jayanti', 'NATIONAL');
INSERT INTO HOLIDAY (HOLIDAY_DATE,REASON,TYPE) VALUES('16th Oct', 'Happy Durga Puja', 'FESTIVAL');
INSERT INTO HOLIDAY (HOLIDAY_DATE,REASON,TYPE) VALUES('4th Nov', 'Happy Diwali', 'FESTIVAL');


INSERT INTO ROLES (ROLE_ID,ROLE_NAME,CREATED_AT,CREATED_BY) VALUES(1,'ADMIN',SYSDATE,'SUSHIL');
INSERT INTO ROLES (ROLE_ID,ROLE_NAME,CREATED_AT,CREATED_BY) VALUES(2,'STUDENT',SYSDATE,'SUSHIL');