This is not used anymore as we are creating table manually in oracle db, but I just pasted the queries.

CREATE TABLE CONTACT_MSG(
CONTACT_ID INT PRIMARY KEY,
NAME VARCHAR(100) NOT NULL,
MOBILE_NUM VARCHAR(10) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
SUBJECT VARCHAR(100) NOT NULL,
MESSAGE VARCHAR(500) NOT NULL,
STATUS VARCHAR(50) NOT NULL,
CREATED_AT TIMESTAMP NOT NULL,
CREATED_BY VARCHAR(50) NOT NULL,
UPDATED_AT TIMESTAMP DEFAULT NULL,
UPDATED_BY VARCHAR(50) DEFAULT NULL
);

CREATE TABLE HOLIDAY(
HOLIDAY_DATE VARCHAR(50) NOT NULL,
REASON VARCHAR(100)  NOT NULL,
TYPE VARCHAR(20) NOT NULL
);

CREATE SEQUENCE contact_id_seq START WITH 1;

CREATE TABLE ROLES(
ROLE_ID INT PRIMARY KEY,
ROLE_NAME VARCHAR(30) NOT NULL,
CREATED_AT TIMESTAMP NOT NULL,
CREATED_BY VARCHAR(50) NOT NULL,
UPDATED_AT TIMESTAMP DEFAULT NULL,
UPDATED_BY VARCHAR(50) DEFAULT NULL
);

CREATE TABLE ADDRESS(
ADDRESS_ID INT PRIMARY KEY,
ADDRESS1 VARCHAR(200) NOT NULL,
ADDRESS2 VARCHAR(200) DEFAULT NULL,
CITY VARCHAR(50) NOT NULL,
STATE VARCHAR(50) NOT NULL,
ZIP_CODE INT NOT NULL,
CREATED_AT TIMESTAMP NOT NULL,
CREATED_BY VARCHAR(50) NOT NULL,
UPDATED_AT TIMESTAMP DEFAULT NULL,
UPDATED_BY VARCHAR(50) DEFAULT NULL
);

CREATE TABLE PERSON(
PERSON_ID INT PRIMARY KEY,
NAME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(100) DEFAULT NULL,
MOBILE_NUM VARCHAR(50) NOT NULL,
PWD VARCHAR(50) NOT NULL,
ROLE_ID INT NOT NULL,
ADDRESS_ID INT NULL,
CREATED_AT TIMESTAMP NOT NULL,
CREATED_BY VARCHAR(50) NOT NULL,
UPDATED_AT TIMESTAMP DEFAULT NULL,
UPDATED_BY VARCHAR(50) DEFAULT NULL
);

CREATE TABLE CLASS(
CLASS_ID INT PRIMARY KEY,
NAME VARCHAR(100) NOT NULL,
CREATED_AT TIMESTAMP NOT NULL,
CREATED_BY VARCHAR(50) NOT NULL,
UPDATED_AT TIMESTAMP DEFAULT NULL,
UPDATED_BY VARCHAR(50) DEFAULT NULL
);

ALTER TABLE PERSON ADD CLASS_ID INT NULL;
ALTER TABLE PERSON ADD FOREIGN KEY(CLASS_ID) REFERENCES CLASS(CLASS_ID);
ALTER TABLE PERSON ADD FOREIGN KEY(ROLE_ID) REFERENCES ROLES(ROLE_ID);
ALTER TABLE PERSON ADD FOREIGN KEY(ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID);

CREATE SEQUENCE role_id_seq START WITH 1;
CREATE SEQUENCE address_id_seq START WITH 1;
CREATE SEQUENCE person_id_seq START WITH 1;
CREATE SEQUENCE class_id_seq START WITH 1;